const bankruptcy = [
    {
        "Name": "Flutter & Dart - The Complete Guide [2021 Edition]",
        "Price": 30,
        "Rating": 4.6,
        "Enrollment": "1121",
        "Description": "Join the most comprehensive & bestselling Flutter course and learn how to build amazing iOS and Android apps!\n\nYou don't need to learn Android/ Java and iOS/ Swift to build real native mobile apps!\n\nFlutter - a framework developed by Google - allows you to learn one language (Dart) and build beautiful native mobile apps in no time. Flutter is a SDK providing the tooling to compile Dart code into native code and it also gives you a rich set of pre-built and pre-styled UI elements (so called widgets) which you can use to compose your user interfaces.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393308/dev1_bxujco.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Maximilian Schwarzmüller",
        "Category": "Developement",
        "Number": 1,
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "max@gmail.com",
        "Website": "http://www.max.com",
        "Won": "930"
      },
      {
        "Name": "React - The Complete Guide (incl Hooks, React Router, Redux)",
        "Price": 30,
        "Rating": 4.6,
        "Enrollment": "1565",
        "Description": "Learn React or dive deeper into it. Learn the theory, solve assignments, practice in demo projects and build one big application which is improved throughout the course: The Burger Builder!",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393478/dev2_yt66cp.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Alan Doet",
        "Category": "Developement",
        "Number": 1,
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "alan@gmail.com",
        "Website": "http://www.alan.com",
        "Won": "930"
      },
      {
        "Name": "The Beginner's Guide to Artificial Intelligence in Unity.",
        "Price": 42,
        "Rating": 4.7,
        "Enrollment": "2014",
        "Description": "Do your non-player characters lack drive and ambition? Are they slow, stupid and constantly banging their heads against the wall? Then this course is for you. Join Penny as she explains, demonstrates and assists you in creating your very own NPCs in Unity with C#. All you need is a sound knowledge of Unity, C# and the ability to add two numbers together.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393479/dev3_sfki4i.jpg",
        "Discount": "72%(Original:1000)",
        "Courseprovider": "Penny de Byl",
        "Category": "Developement",
        "Number": 1,
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "penny@gmail.com",
        "Website": "http://www.penny.com",
        "Won": "930"
      },
      {
        "Name": "Unreal Engine 4: The Complete Beginner's Course",
        "Price": 28,
        "Rating": 4.4,
        "Enrollment": "2951",
        "Description": "Learn game development with Unreal Engine 4. UE4 is the industry-leading 3D game design software that the professionals use to create today’s top games. Start your journey towards getting paid to make video games today!",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393553/dev4_zwivcj.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "David Nixon",
        "Category": "Developement",
        "Number": 1,
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "david@gmail.com",
        "Website": "http://www.david.com",
        "Won": "930"
      },
      {
        "Name": "The Complete Android N Developer Course",
        "Price": 32,
        "Rating": 4.4,
        "Enrollment": "1480",
        "Description": "Learn Android App Development with Android 7 Nougat by building real apps including Uber, Whatsapp and Instagram! Become a professional app developer, take freelance gigs and work from anywhere in the world.Submit your apps to Google Play and generate revenue with Google Pay and Google Ads.A huge range of technologies are covered, including open source Parse Server, Firebase, Admob, GDX (game development), Bluetooth and a whole lot more.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393554/dev5_dkebrn.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Rob Percival",
        "Category": "Developement",
        "Number": 1,
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "rob@gmail.com",
        "Website": "http://www.rob.com",
        "Won": "930"
      }
]
export default bankruptcy;