const civilLawyers=[
    {
        "Name": "Ultimate Adobe Photoshop Training: From Beginner to Pro”",
        "Price": 50,
        "Rating": 4.6,
        "Enrollment": "3872",
        "Description": "This is the ultimate Photoshop training course that will take you from absolute beginner to proficien Learn how to use the program with ease while having fun! My approach is simple: we focus on real world cases and I present the best techniques that require minimal effort yet produce maximum results. All my content is focused on getting the job done in the least amount of time possible. I'll be using the latest version of the program - Photoshop CC 2021, but all the content is explained for all users, no matter what version you have installed.”",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393664/des2_cuqumf.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Cristian Doru Barin",
        "Category": "Design",
        "Number": 2,        
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "chris@gmail.com",
        "Website": "http://www.chris.com",
        "Won": "930"
      },
      {
        "Name": "Sketch from A to Z (2020): Become an app designer",
        "Price": 68,
        "Rating": 4.7,
        "Enrollment": 2946,
        "Description": "Learn to Design Beautiful, High-Quality Mobile Application UI with Sketch's Powerful Tools and Smooth Workflow Master the essential principles and tools of Sketch. Discover design techniques that will enhance your creative potential. Learn and implementUI best practices to ensure quality and usability. Journey from concept to completion by creating a sample mobile application.”",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393663/des3_olpxzm.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Joseph Angelo Todaro",
        "Category": "Design",
        "Number": 2,
        
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "joseph@gmail.com",
        "Website": "http://www.joseph.com",
        "Won": "930"
      },
      {
        "Name": "Graphic Design Bootcamp: Photoshop, Illustrator, InDesign",
        "Price": 42,
        "Rating": 4.5,
        "Enrollment": "1221",
        "Description": "This course is for anyone who is interested in becoming a graphic designer, and especially geared towards beginners. When you enroll in this course, you will have access to over 15 hours of on-demand content, as well as the opportunity to join a private Facebook group with over 13,000 members.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393664/des4_zkndbt.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Derrick Mitchell",
        "Category": "Design",
        "Number": 2,        
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "derrick@gmail.com",
        "Website": "http://www.derrick.com",
        "Won": "930"
      },
      {
        "Name": "Illustrator 2020 MasterClass",
        "Price": 40,
        "Rating": 4.6,
        "Enrollment": "1231",
        "Description": "This course has been purposely designed for users of all experiences, from complete beginners to existing Illustrator users, who want to take their skills to the next level. Being able to confidently work in Illustrator is an essential skill for any Graphic Designer or Illustrator, but it is an equally useful tool for Product Designers, Fashion Designers, UI/UX designers and various other areas within and outside of the creative industry.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393664/des5_h5ctrn.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Martin Perhiniak",
        "Category": "Design",
        "Number": 2,        
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "martin@gmail.com",
        "Website": "http://www.martin.com",
        "Won": "930"
      },
]
export default civilLawyers;