const corporate=[
    {
        "Name": "The Complete Digital Marketing Course - 12 Courses in 1",
        "Price": 42,
        "Rating": 4.5,
        "Enrollment": "5252",
        "Description": "Master Digital Marketing Strategy, Social Media Marketing, SEO, YouTube, Email, Facebook Marketing, Analytics & More! Join 400,000+ students in the bestselling digital marketing course on Udemy!\n    With over 20 hours of training, quizzes and practical steps you can follow - this is one of the most comprehensive digital marketing courses available. We'll cover SEO, YouTube Marketing, Facebook Marketing, Google Adwords, Google Analytics and more!\n    Learn By Doing\n    The course is hugely interactive with projects, checklists & actionable lectures built into every section.Learn step by step how to market a business online from scratch across all the major marketing. Follow the steps on screen to get results at work, for own business or for your digital marketing clients.\n    12 Courses in 1\n    Covering 12 major online marketing topics and comprising of 20+ hours of clear cut lectures & practice activities - this course is \"incredible value for money!\" as one student said. We'll Market Research. Ask 3 simple questions to validate your business  WordPress. Build a world-class website in 1 hour without any  Email Marketing. Build a mailing list of 1000 people in 30 days from scratch.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393824/marr1_uwf7fv.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Rob Percival, Daragh Walsh",
        "Category": "Marketing",
        "Number": 3,        
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "rob@gmail.com",
        "Website": "http://www.rob.com",
        "Won": "930"
      },
      {
        "Name": "Ultimate Google Ads Training 2020: Profit with Pay Per Click",
        "Price": 48,
        "Rating": 4.5,
        "Enrollment": "1668",
        "Description": "Google Ads 2020: How our clients have transformed their sales using Google Ads & get your Google Ads certification! \n    Win back your business from your competition by really learning Google AdWords like an expert. This Google AdWords Course has the *HIGHEST STUDENT SATISFACTION RATING in Udemy's entire marketing and advertising section! *(Reported by Udemy)\n    Welcome to Udemy's highest rated AdWords course of all time.\n    Over 99,000 business owners, students, marketing specialists and entrepreneurs have enrolled writing in thousands of 5 star reviews\n    Learn How To Drive Consistent, Reliable, High-Quality Traffic To Your Site Every Single Day With Google AdWords!\n    Your customers are using Google every single day to search for the products and services you offer, but you're losing business to your competition because their AdWords campaigns are more optimized than yours are.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393825/marr2_xif3ry.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Isaac Rudansky",
        "Category": "Marketing",
        "Number": 3,        
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "isaac@gmail.com",
        "Website": "http://www.isaac.com",
        "Won": "930"
      },
      {
        "Name": "Facebook Ads & Facebook Marketing MASTERY 2021 | Coursenvy",
        "Price": 36,
        "Rating": 4.5,
        "Enrollment": "1656",
        "Description": "Facebook Marketing from beginner to advanced! Join 100,000+ students who MASTERED Facebook and are Facebook Ads experts! \n    Want to become a Facebook Ads expert? JOIN THE 500+ COMPANIES I HAVE CONSULTED ON SOCIAL MEDIA MARKETING AND INCREASED CONVERSIONS FOR VIA FACEBOOK AND INSTAGRAM ADS! Facebook Marketing is a REQUIRED skill for anyone with a business, product, service, brand, or public figure they need to PROMOTE! Join our 300,000+ modMBA students who have MASTERED Facebook advertising with this COMPLETE Facebook Marketing Mastery Course! \n        Three reasons to TAKE THIS COURSE right now! \n    You get lifetime access to lectures!\n    You can ask me questions and see me respond to every single one of them thoughtfully!",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393825/marr3_ucxzfl.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Envy",
        "Category": "Marketing",
        "Number": 3,        
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "envy@gmail.com",
        "Website": "http://www.envy.com",
        "Won": "930"
      },
      {
        "Name": "Instagram Marketing 2021: Complete Guide To Instagram Growth",
        "Price": 36,
        "Rating": 4.5,
        "Enrollment": "1363",
        "Description": "nstagram is a small time investment for a huge customer return!\n    Once you spend just a few hours learning the powerful proven Instagram marketing techniques, you will see why we are the recommend course. We have easy to follow step by step techniques to grow your followers and market your business.\n    Your time will pay off by reaching thousands of new customers, and building a strong, trustworthy relationship through Instagram will skyrocket your brand awareness to a level beyond your expectations. You will have the tools to create quality content, grow your Instagram followers and market your business to these hyper-targeted customers.\n    When making a purchasing decision, people online use your social media presence as a measure of the quality, and trustworthiness of your business. Nothing speaks trust and quality louder than having a thousands of targeted, real, and loving Instagram followers on your profile (of which you can contact at any time!) Your profile will be professional and compelling and you will be using stories, live streaming and all the other new features Instagram releases.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393825/marr4_lsrxqu.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Benjamin Wilson, Entrepreneur Academy",
        "Category": "Marketing",
        "Number": 3,        
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "david@gmail.com",
        "Website": "http://www.david.com",
        "Won": "930"
      },
      {
        "Name": "Social Media Marketing MASTERY | Learn Ads on 10+ Platforms",
        "Price": 38,
        "Rating": 4.5,
        "Enrollment": "1542",
        "Description": "MASTER online marketing on Twitter, Pinterest, Instagram, YouTube, Facebook, Google and more ad platforms! Coursenvy ® \n    If you want to be successful with Social Media Marketing you will LOVE this Udemy course! You will learn the principles and strategies that work for us and that we have used to build highly converting ads for over 500+ businesses and clients successfully! Facebook, Twitter, Instagram, Pinterest, Google, YouTube, LinkedIn, Tumblr, Wordpress, Blogger... any marketing via social media, we have you covered with this top-rated course! Stop wasting your money blindly running ads. MASTER paid online marketing once and for all! The optimization of your social media accounts is a REQUIRED skill for ALL marketers and business owners. TAKE ACTION and learn social media marketing on 10+ platforms starting today!\n    JOIN THE 100,000+ HAPPY STUDENTS I HAVE TAUGHT SOCIAL MEDIA MARKETING!\n    Do you want to partake in a CONSTANTLY updated Social Media Marketing course that teaches you paid advertising and online marketing skills required for over TEN Social Media Platforms? Learn social media ads from A to Z all in one place!\n        Three reasons to TAKE THIS COURSE right now! \n    You get lifetime access to lectures.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610393825/marr5_jcbtqy.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Envy",
        "Category": "Marketing",
        "Number": 3,        
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "envy@gmail.com",
        "Website": "http://www.envy.com",
        "Won": "930"
      },
      
]
export default corporate;