const family = [
    {
        "Name": "Intermediate Blues Rhythm Guitar",
        "Price": 52,
        "Rating": 4.6,
        "Enrollment": "1442",
        "Description": "l Welcome to Intermediate Blues Rhythm Guitar! That's right, no fancy titles or gimmicks here...just straight up blues rhythm! I developed this course to be a direct companion to my release Beginning Blues Rhythm Guitar. This course will be a natural progression from the basics you may already know and, will fully prepare you to play just about any blues song.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610394176/mus1_zrbqlf.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Corey Congilio, Erich Andreas",
        "Category": "Music",
        "Number": 5,
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "corey@gmail.com",
        "Website": "http://www.corey.com",
        "Won": "930"
      },
      {
        "Name": "Pianoforall - Incredible New Way To Learn Piano & Keyboard",
        "Price": 50,
        "Rating": 4.6,
        "Enrollment": "2917",
        "Description": "l Pianoforall is specially designed to take complete beginners to an intermediate level faster than any other method. You start with popular rhythm style piano (think of artists like Lennon & McCartney, Elton John, Billy Joel, Barry Mannilow, Lionel Ritchie, Coldplay, Norah Jones and so on) which means you get to sound like a pro right from the start.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610394178/mus2_vheegv.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Robin Hall",
        "Category": "Music",
        "Number": 5,
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "robin@gmail.com",
        "Website": "http://www.robin.com",
        "Won": "930"
      },
      {
        "Name": "The Complete Piano Chords Course | Beginner to Advanced",
        "Price": 62,
        "Rating": 5,
        "Enrollment": "3245",
        "Description": "l Imagine being able to sit down at a piano or keyboard and PLAY any song without the need to read sheet music? Now you can easily achieve this within weeks not years and without wasting too much money, time, and effort on traditional Piano Lessons.The course is carefully structured to take absolute beginners with no previous training in Piano or Keyboard to the advanced level within a relatively short period of time.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610394177/mus3_hmmdhs.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Kingsley B-Nkrumah",
        "Category": "Music",
        "Number": 5,
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "kirill@gmail.com",
        "Website": "http://www.kirill.com",
        "Won": "930"
      },
      {
        "Name": "Music Theory for Electronic Producers - The Complete Course!",
        "Price": 36,
        "Rating": 4.4,
        "Enrollment": "1014",
        "Description": "l In this course, you will gain a deep understanding of Music Theory and ideas techniques and formulas to use when creating your own electronic music to allow you more options. You'll learn the beauty and the power of music theory that's used by professionals today. With over 8-hours of video, this music course is JAM PACKED with information to help you learn music theory to help you improve at music theory today!",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610394177/mus4_dlcfes.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Tomas George",
        "Category": "Music",
        "Number": 5,
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "digitalmaster@gmail.com",
        "Website": "http://www.digitalmaster.com",
        "Won": "930"
      },
      {
        "Name": "SINGING SIMPLIFIED #1: The Fast-Track to Singing Like a Pro",
        "Price": 42,
        "Rating": 4.6,
        "Enrollment": "2127",
        "Description": "l SINGING SIMPLIFIED will get you on your way to becoming an excellent singer... faster than you thought possible! Believe it or not, you already have the \"built-in\" ability to be a great singer. You were born with a natural vocal range and I'm going to help you to tap into it - quickly and easily, while having FUN of course! We'll combine technique and everyday emotive sounds in your vocal training to help you understand that singing isn't as difficult or scary as you thought it was.",
        "Image": "https://res.cloudinary.com/dmxitcrjx/image/upload/v1610394178/mus5_h7uopn.jpg",
        "Discount": "96%(Original:8640)",
        "Courseprovider": "Steve Glazer",
        "Category": "Music",
        "Number": 5,
        "Age" : 52,
        "DP": "https://cdn.blrankings.com/best-lawyers/lawyer-images/peter-d-anderson-39650?t=2021021118203803",
        "Email" : "steve@gmail.com",
        "Website": "http://www.steve.com",
        "Won": "930"
      }
]

export default family;